export const NODE = {
  ACTION: 'action',
  DOCUMENT: 'document'
};

export const ACTIONS = {
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_ERROR: 'FETCH_ERROR'
};

export const FETCHES = {
  DOCUMENT_INDEX_GET: 'DOCUMENT_INDEX_GET',
  DOCUMENT_INDEX_SEARCH: 'DOCUMENT_INDEX_SEARCH',
  DOCUMENT_GET: 'DOCUMENT_GET',
  COMMENT_ADD: 'COMMENT_ADD'
};

